gtest: resolve build fail with clang
To utilize AddressSanitizer, we shall allow the full compilation with
clang in advance. However, clang complains as following:

tests/unit_test/c/gtest-1.7.0/include/gtest/gtest.h:1577:28:
error: comparison between pointer and
      integer ('_IO_FILE *' and 'long')
GTEST_IMPL_CMP_HELPER_(NE, !=);
~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
tests/unit_test/c/gtest-1.7.0/include/gtest/gtest.h:1562:12:
note: expanded from macro
      'GTEST_IMPL_CMP_HELPER_'
  if (val1 op val2) {\
      ~~~~ ^  ~~~~

This patch fix build fail by introducing proper casts.